### ISSUE TITLE
README

### ISSUE THREAD

**Issue by unicodeveloper** [andela-cijeomah/naijaemoji#1]
Credits

Simple ORM is maintained by Chidozie Ijeomah.

License

Simple ORM is released under the MIT Licence. See the bundled LICENSE file for details.

Why am i seeing simple ORM here?

**Comment by unicodeveloper** [comment]
The ReadMe is very incomplete, there is no Usage guide that clearly states all the routes and the kind of responses. How does the programmer or any other person know the  kind of routes available if there is no documentation?

I can't kind even test your app because I can't see the documentation here. Kindly fix ASAP!

**Comment by unicodeveloper** [comment]
@andela-cijeomah you haven't fixed this yet

**Comment by bendozy** [comment]
Fixed
